image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: of  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - chmod +x gradlew

on:
jobs:
build_script:
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации
  
