name: Java CI with Gradle

branches:
  - only:
      main  # ветка git
    
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Build with Gradle
        run: chmod +x gradlew
      - install:
          # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
          chmod +x gradlew
      - build_script:
          ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации
